using Newtonsoft.Json.Converters;

namespace Refresh.GameServer.Types.Telemetry.Json.Events;

[JsonConverter(typeof(StringEnumConverter))]
public enum TelemetryInventoryClickAction // ps4 01.28 0x01ef1186
{
    ACTION_NONE,
    ACTION_CREATE,
    ACTION_CREATE_PRIMTIIVE,
    ACTION_FLOOD_FILL,
    ACTION_SET_EMITTER_OBJECT,
    ACTION_SET_GUN_OBJECT,
    ACTION_SET_EGG_CONTENTS,
    ACTION_ADD_COMPLETE_REWARD,
    ACTION_ADD_COLLECT_REWARD,
    ACTION_ADD_ACE_REWARD,
    ACTION_SET_STICKER_SWITCH_REF,
    ACTION_SET_SHAPE_STICKER_CUTTER,
    ACTION_SET_LEVEL_LINK,
    ACTION_RANDOMISE_COSTUME,
    ACTION_RANDOMISE_NPC_COSTUME,
    ACTION_EDIT_PAINTING,
    ACTION_SET_PAINTING_BACKGROUND,
    ACTION_SET_PAINTING_STICKER_BRUSH,
    ACTION_POPPET_POWERUP,
    ACTION_SET_POCKET_ITEM,
    ACTION_SET_POCKET_SENSOR,
    ACTION_SET_POWER_UP_OBJECT,
    ACTION_SET_POWER_UP_COSTUME,
    ACTION_CREATE_GAMEKIT,
    ACTION_SET_SACKBOT_MESH,
    ACTION_LEVEL_IMPORTER,
    ACTION_SET_MATERIAL,
}